name: HA Redirect
version: "1.0.0"
slug: ha_redirect
description: Minimal TCP port forward to Home Assistant
url: https://github.com/pallemannen/hass-addons/tree/main/ha_redirect
arch:
  - aarch64
  - amd64
init: false
startup: services
boot: auto
host_network: true
options:
  target_port: 8123
  listen_ports: "80,8080,443,8443,8123"
schema:
  target_port: port
  listen_ports: str
